# Cloudflare Wrangler config for Pages Functions + D1
name = "wookstars-api"
compatibility_date = "2025-12-01"

[[r2_buckets]]
binding = "VIDEOS"
bucket_name = "wookstars-videos"

[[d1_databases]]
binding = "DB"
database_name = "wookstars-db"
database_id = "d4022eca-b0e3-452e-b356-0c8a56e2bee8"